name: Build, Test and Package Snapshots

on:
  push

jobs:
  build_for_windows:
    runs-on: windows-2019
    name: Build for Windows
    steps:
    - uses: actions/checkout@v2
    - name: Make
      run: make
      env:
        CC: gcc
        SUFFIX: .exe
        SERIAL: windows/serial.c
    - run: |
        mkdir -p artifacts/windows
        cp dump_2600.exe artifacts/windows/dump_2600.exe
    - uses: actions/upload-artifact@v2
      with :
        name: dump_2600 snapshot builds
        path: artifacts

  build_for_linux:
    runs-on: ubuntu-18.04
    name: Build for Linux
    steps:
    - uses: actions/checkout@v2
    - name: Make
      run: make
      env:
        CC: gcc
    - run: |
        mkdir -p artifacts/linux
        cp dump_2600 artifacts/linux/dump_2600
    - uses: actions/upload-artifact@v2
      with :
        name: dump_2600 snapshot builds
        path: artifacts
        